### ISSUE TITLE
Doesn't send add-on config correctly

### ISSUE THREAD

**Issue by jsonmaur** [terraform-providers/terraform-provider-heroku#12] opened 2017-07-23 00:48 UTC
### Terraform Version
v0.9.11

### Affected Resource(s)
- heroku_addon

### Terraform Configuration Files
```hcl
resource "heroku_addon" "postgres" {
  app = "${heroku_app.main.name}"
  plan = "heroku-postgresql:hobby-dev"
  config {
    as = "POSTGRES_URL"
  }
}
```

### Expected Behavior
Should create a database add-on with the environment variable set to `POSTGRES_URL`.

### Actual Behavior
Created the database add-on with the environment variable set to the default of `DATABASE_URL`. Looking at the state file, it stores this value in `config_vars`, but if I try to set that value instead of `config`, I get the error: `"config_vars": this field cannot be set`.

For reference: https://devcenter.heroku.com/articles/add-ons

**Comment by davidji99** [comment] 2018-10-26 07:45
From internal discussionsthe `config` attribute on heroku_addon isn't used to rename the addon's environment variable. It is used to set a 'config' of the addon say what version of the addon to use. For example, in the sample request https://devcenter.heroku.com/articles/platform-api-reference#add-on-create, we want the add-on to use a specific version:

```
  "config": {
    "db-version": "1.2.3"
  },
```

Also, `config` does not function like the `AS` in this CLI command:

```
heroku addons:attach important-redis --app important-app --as SESSION_STORE
```

So as far as I can tell, the `config` is working as intended. Closing this issue for now. Feel free to re-open if needed.

**Closed by davidji99** 2018-10-26 07:45 UTC
Labels: bug
